#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# WAGNER AG
# Developer: opensource@wagner.ch

"""
Check_MK agent based checks to be used with agent_fortios Datasource
"""

from __future__ import annotations

import time
from collections.abc import Mapping
from typing import Any

from cmk.agent_based.v2.render import networkbandwidth

from cmk.agent_based.v2 import (
    CheckPlugin,
    CheckResult,
    DiscoveryResult,
    Metric,
    Result,
    Service,
    State,
    check_levels,
    get_rate,
    get_value_store,
)

from .fortios_ipsec import FortiIPSec


def get_ignored_tunnels(ipsec_tunnel: FortiIPSec, tunnel_ignored_names: list[str], tunnel_ignored_dst_subnets: list[str]):
    ignored_tunnels = []

    for proxy_source in ipsec_tunnel.proxyid:
        # Add p2 tunnels matching destinations subnets to ignored tunnel list
        for proxy in proxy_source.proxy_dst or []:
            if proxy.subnet in tunnel_ignored_dst_subnets:
                ignored_tunnels.append(proxy_source)
                break

        # Add p2 tunnels matching tunnel names to ignored tunnel list
        if proxy_source.p2name in tunnel_ignored_names and proxy_source not in ignored_tunnels:
            ignored_tunnels.append(proxy_source)

    return ignored_tunnels


def _get_effective_proxy_sources(
    ipsec_tunnel: FortiIPSec,
    tunnel_ignored_names: list[str],
    tunnel_ignored_dst_subnets: list[str],
):
    ignored_tunnels = get_ignored_tunnels(ipsec_tunnel, tunnel_ignored_names, tunnel_ignored_dst_subnets)
    effective_proxy_sources = [proxy for proxy in ipsec_tunnel.proxyid if proxy not in ignored_tunnels]
    return effective_proxy_sources, ignored_tunnels


def _tunnel_is_effectively_up(
    ipsec_tunnel: FortiIPSec,
    tunnel_ignored_names: list[str],
    tunnel_ignored_dst_subnets: list[str],
) -> tuple[bool, list, int, int, int]:
    effective_proxy_sources, ignored_tunnels = _get_effective_proxy_sources(
        ipsec_tunnel,
        tunnel_ignored_names,
        tunnel_ignored_dst_subnets,
    )

    effective_total = len(effective_proxy_sources)
    effective_up = sum(1 for proxy in effective_proxy_sources if proxy.status == "up")
    effective_down = sum(1 for proxy in effective_proxy_sources if proxy.status == "down")

    # If every phase2 entry is intentionally ignored, the tunnel should not alert.
    if effective_total == 0:
        return True, ignored_tunnels, effective_total, effective_up, effective_down

    return effective_up == effective_total, ignored_tunnels, effective_total, effective_up, effective_down


def _normalize_group_members(current_item: str, configured_members: list[str]) -> list[str]:
    normalized_members: list[str] = []
    for member in [current_item, *configured_members]:
        member = member.strip()
        if member and member not in normalized_members:
            normalized_members.append(member)
    return normalized_members


def discovery_fortios_ipsec(section: Mapping[str, FortiIPSec]) -> DiscoveryResult:
    for item in section:
        # in case of red devices, ignore the autogenerated parent tunnels
        tunnel = section.get(item)
        if tunnel is not None and tunnel.fct_uid is None and tunnel.type != "":
            yield Service(item=item)


def check_fortios_ipsec(item: str, params: Mapping[str, Any], section: Mapping[str, FortiIPSec]) -> CheckResult:
    if (ipsec_tunnel := section.get(item)) is None:
        yield Result(
            state=State.UNKNOWN,
            summary=f"Tunnel {item} is missing",
        )
        return

    tunnel_ignored_names = params.get("item_names_excluded", [])
    tunnel_ignored_dst_subnets = params.get("item_dst_excluded", [])
    redundancy_group_members = params.get("redundancy_group_members", [])
    redundancy_group_name = params.get("redundancy_group_name", "")

    tunnel_is_up, ignored_tunnels, effective_total, effective_up, effective_down = _tunnel_is_effectively_up(
        ipsec_tunnel,
        tunnel_ignored_names,
        tunnel_ignored_dst_subnets,
    )

    up_tunnels = [
        f"{proxy.p2name}: {[dest.subnet for dest in proxy.proxy_dst or []]}"
        for proxy in ipsec_tunnel.proxyid
        if proxy.status == "up"
    ]
    down_tunnels = [
        f"{proxy.p2name}: {[dest.subnet for dest in proxy.proxy_dst or []]}"
        for proxy in ipsec_tunnel.proxyid
        if proxy.status == "down"
    ]

    details = f"""Tunnels up: [{", ".join(up_tunnels)}], 

                Tunnels down: [{", ".join(down_tunnels)}], 

                Tunnels ignored by name: [{", ".join(tunnel_ignored_names)}], 

                Tunnels ignored by destination subnet: [{", ".join(tunnel_ignored_dst_subnets)}], 

                Effective phase2 tunnels: {effective_total}, effective up: {effective_up}, effective down: {effective_down}, 

                """

    group_members = _normalize_group_members(item, redundancy_group_members)
    if len(group_members) > 1:
        group_name = redundancy_group_name.strip() or " / ".join(group_members)
        group_states: dict[str, bool] = {}
        missing_members: list[str] = []

        for member in group_members:
            group_tunnel = section.get(member)
            if group_tunnel is None:
                missing_members.append(member)
                continue

            member_is_up, _, _, _, _ = _tunnel_is_effectively_up(
                group_tunnel,
                tunnel_ignored_names,
                tunnel_ignored_dst_subnets,
            )
            group_states[member] = member_is_up

        members_up = [member for member, is_up in group_states.items() if is_up]
        members_down = [member for member, is_up in group_states.items() if not is_up]

        group_details = (
            details
            + f"Redundancy group: {group_name}, \n"
            + f"Configured members: [{', '.join(group_members)}], \n"
            + f"Members up: [{', '.join(members_up)}], \n"
            + f"Members down: [{', '.join(members_down)}], \n"
            + f"Missing members: [{', '.join(missing_members)}]"
        )

        if members_up:
            summary = (
                f"Redundancy group '{group_name}' healthy - active member(s): {', '.join(members_up)}; "
                f"current tunnel '{item}' is {'up' if tunnel_is_up else 'down'}"
            )
            yield Result(state=State.OK, summary=summary, details=group_details)
        else:
            known_members = len(group_states)
            expected_members = len(group_members)
            summary = (
                f"Redundancy group '{group_name}' down - all {known_members}/{expected_members} known member(s) are down"
            )
            if missing_members:
                summary += f"; missing in agent data: {', '.join(missing_members)}"
            yield Result(state=State.CRIT, summary=summary, details=group_details)
    else:
        if tunnel_is_up:
            if effective_total == 0 and ignored_tunnels:
                yield Result(
                    state=State.OK,
                    summary=f"{ipsec_tunnel.name}: all monitored phase2 entries are ignored by rule",
                    details=details,
                )
            else:
                yield Result(state=State.OK, summary=ipsec_tunnel.summary, details=details)
        else:
            yield Result(state=State.CRIT, summary=ipsec_tunnel.summary, details=details)

    yield from check_levels(
        value=ipsec_tunnel.tunnels_total,
        metric_name="ipsec_total",
        label="Total",
    )
    yield Metric("total_tunnels", ipsec_tunnel.tunnels_total)

    yield from check_levels(
        value=ipsec_tunnel.tunnels_up,
        metric_name="ipsec_up",
        label="Up",
    )
    yield Metric("ipsec_up", ipsec_tunnel.tunnels_up)

    yield from check_levels(
        value=ipsec_tunnel.tunnels_down,
        metric_name="ipsec_down",
        label="Down",
    )

    yield Metric("ipsec_down", ipsec_tunnel.tunnels_down)

    yield from check_levels(
        value=len(ignored_tunnels),
        metric_name="ipsec_ignored",
        label="Ignored",
    )

    yield Metric("ipsec_ignored", len(ignored_tunnels))

    yield from check_levels(
        value=ipsec_tunnel.connection_count,
        metric_name="ipsec_connections",
        label="Connection count",
    )
    yield Metric("ipsec_connections", ipsec_tunnel.connection_count)

    value_store = get_value_store()
    if ipsec_tunnel.incoming_bytes:
        act_time = time.time()
        incoming_bytes = 0
        incoming_bytes = get_rate(value_store, "if_in_bps", act_time, ipsec_tunnel.incoming_bytes)
        yield from check_levels(
            value=incoming_bytes,
            metric_name="if_in_bps",
            render_func=networkbandwidth,
            label="In",
        )
        yield Metric("if_in_bps", value=incoming_bytes)

    if ipsec_tunnel.outgoing_bytes:
        act_time = time.time()
        outgoing_bytes = 0
        outgoing_bytes = get_rate(value_store, "if_out_bps", act_time, ipsec_tunnel.outgoing_bytes)
        yield from check_levels(
            value=outgoing_bytes,
            metric_name="if_out_bps",
            render_func=networkbandwidth,
            label="Out",
        )
        yield Metric("if_out_bps", value=outgoing_bytes)


check_plugin_fortios_ipsec = CheckPlugin(
    name="fortios_ipsec",
    service_name="VPN IPSec Tunnel %s",
    sections=["fortios_ipsec"],
    discovery_function=discovery_fortios_ipsec,
    check_ruleset_name="fortios_ipsec",
    check_default_parameters={},
    check_function=check_fortios_ipsec,
)
